import type {ImageSourcePropType} from 'react-native';

type ImageMap = {
  badge: ImageSourcePropType;
  crazyarcade: ImageSourcePropType;
  crazyarcadeLetter: ImageSourcePropType;
  executiveChooJongWon: ImageSourcePropType;
  executiveChooYeonJin: ImageSourcePropType;
  executiveKimHyungSeok: ImageSourcePropType;
  executiveKimBoRam: ImageSourcePropType;
  executiveParkSungHo: ImageSourcePropType;
  executiveLeeJoonSuck: ImageSourcePropType;
  executiveKangSungGoo: ImageSourcePropType;
  gameFestival1: ImageSourcePropType;
  gameFestival2: ImageSourcePropType;
  gameFestival3: ImageSourcePropType;
  coinBattle1: ImageSourcePropType;
  coinBattle2: ImageSourcePropType;
  coinBattle3: ImageSourcePropType;
  homeBanner: ImageSourcePropType;
  human: ImageSourcePropType;
  logo: ImageSourcePropType;
  poster1: ImageSourcePropType;
  poster2: ImageSourcePropType;
  poster3: ImageSourcePropType;
  poster4: ImageSourcePropType;
  poster5: ImageSourcePropType;
  product1: ImageSourcePropType;
  profile: ImageSourcePropType;
  qrCode: ImageSourcePropType;
  starcraft: ImageSourcePropType;
  starcraftLetter: ImageSourcePropType;
  tekken: ImageSourcePropType;
  tekkenLetter: ImageSourcePropType;
  noti: ImageSourcePropType;
  paper: ImageSourcePropType;
  rock: ImageSourcePropType;
  scissor: ImageSourcePropType;
  tekken7: ImageSourcePropType;
  maskSinger: ImageSourcePropType;
  maskSingerLetter: ImageSourcePropType;
  executive: ImageSourcePropType;
  executiveLetter: ImageSourcePropType;
};

export const image: ImageMap = {
  badge: require('./badge.png'),
  crazyarcade: require('./crazyarcade.png'),
  crazyarcadeLetter: require('./crazyarcade_letter.png'),
  executiveChooJongWon: require('./4.png'),
  executiveChooYeonJin: require('./3.png'),
  executiveKimHyungSeok: require('./2.png'),
  executiveKimBoRam: require('./5.png'),
  executiveParkSungHo: require('./1.png'),
  executiveLeeJoonSuck: require('./6.png'),
  executiveKangSungGoo: require('./7.png'),
  gameFestival1: require('./gameFestival1.jpg'),
  gameFestival2: require('./gameFestival2.jpg'),
  gameFestival3: require('./gameFestival3.jpg'),
  coinBattle1: require('./coinBattle1.png'),
  coinBattle2: require('./coinBattle2.png'),
  coinBattle3: require('./coinBattle3.png'),
  homeBanner: require('./home-banner.png'),
  human: require('./human.png'),
  logo: require('./logo.png'),
  poster1: require('./poster1.png'),
  poster2: require('./poster2.png'),
  poster3: require('./poster3.png'),
  poster4: require('./poster4.png'),
  poster5: require('./poster5.png'),
  product1: require('./product1.png'),
  profile: require('./profile.png'),
  qrCode: require('./qrCode.png'),
  starcraft: require('./starcraft.png'),
  starcraftLetter: require('./starcraft_letter.png'),
  tekken: require('./tekken.png'),
  tekkenLetter: require('./tekken_letter.png'),
  noti: require('./noti.png'),
  paper: require('./paper.png'),
  rock: require('./rock.png'),
  scissor: require('./scissor.png'),
  tekken7: require('./tekken7.png'),
  maskSinger: require('./maskSinger.png'),
  maskSingerLetter: require('./maskSinger_letter.png'),
  executive: require('./executive.png'),
  executiveLetter: require('./executive_letter.png'),
};
